<a href="https://colab.research.google.com/github/Kyle-nguyen0202/Deep_learning/blob/main/Chapter1_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!


In [ ]:
#Initialize two constants
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])
# Multiply
result = tf.multiply(x1,x2)

In [ ]:
result

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [ ]:
tf.print(result)

[5 12 21 32]


In [ ]:
# 1D Tensor
d1 = tf.ones((2,))
tf.print(d1)

[1 1]


In [ ]:
# 2D Tensor
d2 = tf.ones((2,2))
tf.print(d2)

[[1 1]
 [1 1]]


In [ ]:
# 3D Tensor
d3 = tf.ones((2,2,2))
tf.print(d3)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [ ]:
# Constant
a = tf.constant(5.3, name = 'a', dtype=tf.float32)
tf.print('a =\n',a)

a =
 5.3


In [ ]:
b = tf.constant(3, shape=[2,3])
tf.print('b =\n',b)

b =
 [[3 3 3]
 [3 3 3]]


In [ ]:
c = tf.constant([1,2,3,4], shape = [2,2])
tf.print('c =\n',c)

c =
 [[1 2]
 [3 4]]


In [ ]:
d = tf.fill([3,3],7)
tf.print('d =\n',d)

d =
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
e = tf.ones([2,2])
tf.print('e =\n',e)

e =
 [[1 1]
 [1 1]]


In [ ]:
f = tf.zeros_like(c)
tf.print('f =\n',f)

f =
 [[0 0]
 [0 0]]


In [ ]:
# Variables
a0 = tf.Variable([1,2,3,4], dtype = tf.float32)
a1 = tf.Variable([5,6,7,8], dtype = tf.float32)

In [ ]:
c0 = tf.multiply(a0,a1)
tf.print(c0)

[5 12 21 32]


In [ ]:
c1=a0*a1
tf.print(c1)

[5 12 21 32]


In [ ]:
# Operators
a0 = tf.Variable([1,2,3,4], dtype = tf.float32)
a1 = tf.Variable([5,6,7,8], dtype = tf.float32)

In [ ]:
sum1 = tf.add(a0,a1)
tf.print(sum1)

[6 8 10 12]


In [ ]:
diff = tf.subtract(a0,a1)
tf.print(diff)

[-4 -4 -4 -4]


In [ ]:
prod = tf.multiply(a0,a1)
tf.print(a0,a1)

[1 2 3 4] [5 6 7 8]


In [ ]:
quot = tf.divide(a0,a1)
tf.print(quot)

[0.2 0.333333343 0.428571433 0.5]


In [ ]:
x = tf.constant([[-2.25, 4.75],[-3.25, 5.75]])
abs1 = tf.abs(x)
tf.print('Abs:',abs1)

Abs: [[2.25 4.75]
 [3.25 5.75]]


In [ ]:
A = tf.constant([4], tf.int32, name='A')
B = tf.constant([4], tf.int32, name='B')
C = tf.constant([4], tf.int32, name='C')
y1=tf.add_n([A,B,C], name='y1')
tf.print('Add n: ', y1)

Add n:  [12]


In [ ]:
cons1 = tf.constant([1,2])
y = tf.scalar_mul(3, cons1)
tf.print('Scalar Mul: ', y)

Scalar Mul:  [3 6]


In [ ]:
a = tf.constant([4,4,4])
add_n=tf.add_n([a,a,a])
tf.print('Add_n: ', add_n)

Add_n:  [12 12 12]


In [ ]:
neg = tf.negative(a)
tf.print('Negative: ', neg)


Negative:  [-4 -4 -4]
